sudo: required
dist: trusty
language: c
osx_image: xcode9
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
addons:
  apt:
    packages:
      - xz-utils
      - icnsutils
      - graphicsmagick
      - rpm
install:
  - nvm install 6
  - npm install
  - npm prune
script:
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run pack:macos; fi
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf dist/linux-ia32-unpacked && rm -rf dist/linux-unpacked; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf dist/Ao-darwin-x64; fi
deploy:
  provider: releases
  api_key:
    secure: svBBB/MUmG+25t7uNKQAklIMpTzXM4B5Rp+qHnhSxtZU/XmX8ilbrBD6GPmyrwsZN/nzl0XIGWV5lGHarNZRRpJhpnbAxLxewyb9zVy550/jn0Bdt/qV74R5bsGKv9T6u6skKotWIzrxy4s19f5LbKNmIG136Ix/jq2/NOUUB95UHTJtp+aDIKwrYL7HHNZEQazRMP7huboqyJLzmfSGcYm1pH76HLrKUr6vfp6GAQC/yCsJlwjsz/d66wSQsJ9IFeYg6ibU6a43bKDmHBo7FWNULy4xj0EpyAVnv3GctPmjQAzS+NfqBJN0p+9gJ9XJMB5GGRsKpQcaHHN6aP/ajHyxLgSNRhaRbyca2Ja+ISCTBRN3zpQtAfMlW8KDklS6P3w8ODV1i61UP6xp6OQZMNr+nM2prRgEddxdZnJAohlaiMKMsD5QS1DifM86kJa16CWI1UHHbtP+30QUNaksXxGRdFRn2Naekvx1V64gDeicCT3O6DrR6/Eb1yOCcbuFGp1DTJOEn/kKrpuGB5gVFqPioVSlbpX1ghvtxdFJwHBM0UwzpDnuHsxV/bp083fDHRQrKLJRpBEGvGx15axZw31tFb6sbCEppXLhoE5FmBEi7FlyBQmXTs7PUpHq9XRQQBr9xVEsicnbfLJa4jl3QJB8F+eQlmrhz4RkgAslGZI=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
